_wandb:
    value:
        cli_version: 0.24.0
        e:
            abew6pez0ggxh57pmsx27l5162w52ryu:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "11811160064"
                codePath: rl/train_rl.py
                codePathLocal: train_rl.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "419987546112"
                email: 1327149492@qq.com
                executable: /Users/mmai/anaconda3/envs/control/bin/python
                git:
                    commit: 96ed865148c5042094597f9b5abfe9c81672fbaf
                    remote: https://github.com/WaimenMak/Crowd-Control.git
                host: TUD501229
                memory:
                    total: "17179869184"
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/mmai/Devs/Crowd-Control/rl/train_rl.py
                python: CPython 3.11.9
                root: /Users/mmai/Devs/Crowd-Control/rl
                startedAt: "2026-01-29T11:21:29.441557Z"
                writerId: abew6pez0ggxh57pmsx27l5162w52ryu
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
            "4": 3.11.9
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
