_wandb:
    value:
        cli_version: 0.24.0
        e:
            qjovvet71b8l77xg82cqcutalkzw51b1:
                codePath: rl/train_rl.py
                codePathLocal: train_rl.py
                email: 1327149492@qq.com
                executable: /Users/mmai/anaconda3/envs/control/bin/python
                git:
                    commit: 96ed865148c5042094597f9b5abfe9c81672fbaf
                    remote: https://github.com/WaimenMak/Crowd-Control.git
                host: TUD501229
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/mmai/Devs/Crowd-Control/rl/train_rl.py
                python: CPython 3.11.9
                root: /Users/mmai/Devs/Crowd-Control/rl
                startedAt: "2026-01-28T22:18:27.095611Z"
                writerId: qjovvet71b8l77xg82cqcutalkzw51b1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
            "4": 3.11.9
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
