_wandb:
    value:
        cli_version: 0.24.0
        e:
            o3f1bey7wroew1600v6bejcbm8x0a0l3:
                codePath: rl/train_rl.py
                codePathLocal: train_rl.py
                email: 1327149492@qq.com
                executable: /Users/mmai/anaconda3/envs/control/bin/python
                git:
                    commit: 88f7fbab1a3ee65c1bc69c5e8d43986975e3dab1
                    remote: https://github.com/WaimenMak/Crowd-Control.git
                host: TUD501229
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/mmai/Devs/Crowd-Control/rl/train_rl.py
                python: CPython 3.11.9
                root: /Users/mmai/Devs/Crowd-Control/rl
                startedAt: "2026-01-30T13:13:03.791817Z"
                writerId: o3f1bey7wroew1600v6bejcbm8x0a0l3
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
            "4": 3.11.9
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
