_wandb:
    value:
        cli_version: 0.24.0
        e:
            hzs4k7532qlza9nnkmioclhv3486nol8:
                codePath: rl/train_rl.py
                codePathLocal: train_rl.py
                email: 1327149492@qq.com
                executable: /Users/mmai/anaconda3/envs/control/bin/python
                git:
                    commit: 20ac9d7580e6e9fb5dadfb6b542b829d2842c939
                    remote: https://github.com/WaimenMak/Crowd-Control.git
                host: TUD501229
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/mmai/Devs/Crowd-Control/rl/train_rl.py
                python: CPython 3.11.9
                root: /Users/mmai/Devs/Crowd-Control/rl
                startedAt: "2026-01-30T13:30:24.288971Z"
                writerId: hzs4k7532qlza9nnkmioclhv3486nol8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
            "4": 3.11.9
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
