_wandb:
    value:
        cli_version: 0.24.0
        e:
            5bcha0o7at6qoqiyci5hmg9whm8h9at9:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "12884901888"
                codePath: rl/train_rl.py
                codePathLocal: train_rl.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "426194182144"
                email: 1327149492@qq.com
                executable: /Users/mmai/anaconda3/envs/control/bin/python
                git:
                    commit: a27261403a99ffdf5efbc6dced4c0ff5aa6ee4bb
                    remote: https://github.com/WaimenMak/Crowd-Control.git
                host: TUD501229
                memory:
                    total: "17179869184"
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/mmai/Devs/Crowd-Control/rl/train_rl.py
                python: CPython 3.11.9
                root: /Users/mmai/Devs/Crowd-Control/rl
                startedAt: "2026-01-30T10:53:33.883741Z"
                writerId: 5bcha0o7at6qoqiyci5hmg9whm8h9at9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
            "4": 3.11.9
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
